image: registry.gitlab.aws.dev/cm-arg/argot/go-1.20:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

compile:
  tags:
  - arch:amd64
  - size:small
  stage: build
  script:
    - go mod download
    - go build -o bin/compare cmd/compare/*.go
    - go build -o bin/defer cmd/defer/*.go 
    - go build -o bin/dependencies cmd/dependencies/*.go 
    - go build -o bin/maypanic cmd/maypanic/*.go 
    - go build -o bin/packagescan cmd/packagescan/*.go
    - go build -o bin/reachability cmd/reachability/*.go 
    - go build -o bin/render cmd/render/*.go 
    - go build -o bin/static-commands cmd/static-commands/*.go 
    - go build -o bin/statistics cmd/statistics/*.go 
    - go build -o bin/taint cmd/taint/*.go
    - go build -o bin/argot-cli cmd/cli/*.go
  artifacts:
    paths:
      - bin

runtests:
  tags:
  - arch:amd64
  - size:large
  stage: test
  script:
    - go vet ./analysis/...
    - go test -coverprofile=coverage.txt -covermode count ./analysis/...
    - go install github.com/boumenot/gocover-cobertura@latest
    - gocover-cobertura < coverage.txt > coverage.xml 
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

